In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# #1Rock Game

In [2]:
n1 = 5
n2 = 6

In [3]:
Matrix = [[1 for x in range(n1)] for y in range(n2)]

In [4]:
h = len(Matrix)
w = len(Matrix[1])

def play(Matrix):
    for i in range(2,h):
        for j in range(2,w):
            
            if Matrix[i-2][j] == 2 or Matrix[i-1][j] == 2 or Matrix[i][j-2] == 2 or Matrix[i][j-1] == 2:
                Matrix[i][j] = 1
            else:
                Matrix[i][j] = 2
                
play(Matrix)
Matrix

[[1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1],
 [1, 1, 2, 1, 1],
 [1, 1, 1, 2, 1],
 [1, 1, 1, 1, 2],
 [1, 1, 2, 1, 1]]

In [5]:
Matrix[-1][-1]

1

In [6]:
'''Since Matrix[6][5] is True, we conclude the first player shall win for two piles of 5 stones&6 stones.'''

'Since Matrix[6][5] is True, we conclude the first player shall win for two piles of 5 stones&6 stones.'

# #2Minimal Genome Sequence Edit

In [7]:
s1 = ['A','A','T','T','A','A','G']
s2 = ['T','T','A','A','G','C']
C_indel = 1
C_sub = 1
i_s1 = s1[0]
i_s2 = s2[0]

In [8]:
Matrix = np.array([[0 for x in range(len(s1))] for y in range(len(s2))])
if i_s1 != i_s2:
    Matrix[0,0] = min(C_indel,C_sub) #if first elements are not the same
Matrix

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [9]:
first_time = True #if first elements are not the same
for i in range(1,len(s1)):
    if i_s2 != s1[i]:
        Matrix[0,i] = Matrix[0,i-1] + 1
    else:
        if first_time:
            Matrix[0,i] = Matrix[0,i-1]
            first_time = False
        else:
            Matrix[0,i] = Matrix[0,i-1] + 1
Matrix

array([[1, 2, 2, 3, 4, 5, 6],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [10]:
first_time = True #if first elements are not the same
for i in range(1,len(s2)):
    if i_s1 != s2[i]:
        Matrix[i,0] = Matrix[i-1,0] + 1
    else:
        if first_time:
            Matrix[i,0] = Matrix[i-1,0]
            first_time = False
        else:
            Matrix[i,0] = Matrix[i-1,0] + 1
Matrix

array([[1, 2, 2, 3, 4, 5, 6],
       [2, 0, 0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0, 0, 0],
       [3, 0, 0, 0, 0, 0, 0],
       [4, 0, 0, 0, 0, 0, 0],
       [5, 0, 0, 0, 0, 0, 0]])

## Finish the base cases, time to do some real work!

In [11]:
for i in range(1,len(s2)):
    for j in range(1,len(s1)):
        if s2[i] == s1[j]:
            Matrix[i,j] = min(Matrix[i-1,j-1],Matrix[i-1,j]+C_indel,Matrix[i,j-1]+C_indel)
        else:
            Matrix[i,j] = min(Matrix[i-1,j-1]+C_sub,Matrix[i-1,j]+C_indel,Matrix[i,j-1]+C_indel)
Matrix

array([[1, 2, 2, 3, 4, 5, 6],
       [2, 2, 2, 2, 3, 4, 5],
       [2, 2, 3, 3, 2, 3, 4],
       [3, 2, 3, 4, 3, 2, 3],
       [4, 3, 3, 4, 4, 3, 2],
       [5, 4, 4, 4, 5, 4, 3]])

In [12]:
Matrix[-1,-1]

3

In [13]:
'''We conclude that the minimal edit from ['A','A','T','T','A','A','G'] to ['T','T','A','A','G','C'] is 3 when C = 1 and C' = 1!'''

"We conclude that the minimal edit from ['A','A','T','T','A','A','G'] to ['T','T','A','A','G','C'] is 3 when C = 1 and C' = 1!"

# #3Minimal 0s' & 1s' Sequence Edit

In [15]:
s1 = [0,1,0,0,0]
s2 = [1,0,0,0,1,1]
C_indel = 2
C_sub = 3
i_s1 = s1[0]
i_s2 = s2[0]

In [16]:
Matrix = np.array([[0 for x in range(len(s1))] for y in range(len(s2))])
if i_s1 != i_s2:
    Matrix[0,0] = min(C_indel,C_sub) #if first elements are not the same
Matrix

array([[2, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [17]:
first_time = True #if first elements are not the same
for i in range(1,len(s1)):
    if i_s2 != s1[i]:
        Matrix[0,i] = Matrix[0,i-1] + C_indel
    else:
        if first_time:
            Matrix[0,i] = Matrix[0,i-1]
            first_time = False
        else:
            Matrix[0,i] = Matrix[0,i-1] + C_indel
Matrix

array([[2, 2, 4, 6, 8],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [18]:
first_time = True #if first elements are not the same
for i in range(1,len(s2)):
    if i_s1 != s2[i]:
        Matrix[i,0] = Matrix[i-1,0] + C_indel
    else:
        if first_time:
            Matrix[i,0] = Matrix[i-1,0]
            first_time = False
        else:
            Matrix[i,0] = Matrix[i-1,0] + C_indel
Matrix

array([[ 2,  2,  4,  6,  8],
       [ 2,  0,  0,  0,  0],
       [ 4,  0,  0,  0,  0],
       [ 6,  0,  0,  0,  0],
       [ 8,  0,  0,  0,  0],
       [10,  0,  0,  0,  0]])

## Finish the base cases, time to do some real work!

In [19]:
for i in range(1,len(s2)):
    for j in range(1,len(s1)):
        if s2[i] == s1[j]:
            Matrix[i,j] = min(Matrix[i-1,j-1],Matrix[i-1,j]+C_indel,Matrix[i,j-1]+C_indel)
        else:
            Matrix[i,j] = min(Matrix[i-1,j-1]+C_sub,Matrix[i-1,j]+C_indel,Matrix[i,j-1]+C_indel)
Matrix

array([[ 2,  2,  4,  6,  8],
       [ 2,  4,  2,  4,  6],
       [ 4,  5,  4,  2,  4],
       [ 6,  7,  5,  4,  2],
       [ 8,  6,  7,  6,  4],
       [10,  8,  9,  8,  6]])

In [20]:
Matrix[-1,-1]

6

In [21]:
'''We conclude that the minimal edit from [0,1,0,0,0] to [1,0,0,0,1,1] is 6 when C = 2 and C' = 3!'''

"We conclude that the minimal edit from [0,1,0,0,0] to [1,0,0,0,1,1] is 7 when C = 2 and C' = 3!"

# #4Minimal Sequence Edit API

In [23]:
def mini_sequence_edit(s1,s2,C_indel,C_sub):
    i_s1 = s1[0]
    i_s2 = s2[0]
    
    Matrix = np.array([[0 for x in range(len(s1))] for y in range(len(s2))])
    if i_s1 != i_s2:
        Matrix[0,0] = min(C_indel,C_sub) #if first elements are not the same
            
    #base cases massage!
    first_time = True #if first elements are not the same
    for i in range(1,len(s1)):
        if i_s2 != s1[i]:
            Matrix[0,i] = Matrix[0,i-1] + C_indel
        else:
            if first_time:
                Matrix[0,i] = Matrix[0,i-1]
                first_time = False
            else:
                Matrix[0,i] = Matrix[0,i-1] + C_indel
    first_time = True #if first elements are not the same
    for i in range(1,len(s2)):
        if i_s1 != s2[i]:
            Matrix[i,0] = Matrix[i-1,0] + C_indel
        else:
            if first_time:
                Matrix[i,0] = Matrix[i-1,0]
                first_time = False
            else:
                Matrix[i,0] = Matrix[i-1,0] + C_indel
                    
    for i in range(1,len(s2)):
        for j in range(1,len(s1)):
            if s2[i] == s1[j]:
                Matrix[i,j] = min(Matrix[i-1,j-1],Matrix[i-1,j]+C_indel,Matrix[i,j-1]+C_indel)
            else:
                Matrix[i,j] = min(Matrix[i-1,j-1]+C_sub,Matrix[i-1,j]+C_indel,Matrix[i,j-1]+C_indel)
                
    print('''We conclude that the minimal edit from {} to {} is {} when C_indel = {} and C_sub = {}!'''.format(s1,s2,Matrix[-1,-1],C_indel,C_sub))
    return Matrix, Matrix[-1,-1]

In [28]:
Matrix, minimal_edit_number = mini_sequence_edit(s1,s2,C_indel,C_sub)

We conclude that the minimal edit from [0, 1, 0, 0, 0] to [1, 0, 0, 0, 1, 1] is 6 when C_indel = 2 and C_sub = 3!
